import { UserRole } from '@prisma/client'

const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: 'Zaq12wsx',
      role: UserRole.admin,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    // Additional 31 users (3 admins + 28 regular users) for testing
    {
      name: 'Robert Johnson',
      email: 'robert.johnson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Maria Garcia',
      email: 'maria.garcia@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'David Smith',
      email: 'david.smith@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Sarah Williams',
      email: 'sarah.williams@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Michael Brown',
      email: 'michael.brown@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Jennifer Davis',
      email: 'jennifer.davis@example.com',
      password: 'Zaq12wsx',
      role: UserRole.admin,
    },
    {
      name: 'William Miller',
      email: 'william.miller@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Elizabeth Wilson',
      email: 'elizabeth.wilson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'James Moore',
      email: 'james.moore@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Patricia Taylor',
      email: 'patricia.taylor@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Christopher Anderson',
      email: 'christopher.anderson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Linda Thomas',
      email: 'linda.thomas@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Matthew Jackson',
      email: 'matthew.jackson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Barbara White',
      email: 'barbara.white@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Daniel Harris',
      email: 'daniel.harris@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Susan Martin',
      email: 'susan.martin@example.com',
      password: 'Zaq12wsx',
      role: UserRole.admin,
    },
    {
      name: 'Joseph Thompson',
      email: 'joseph.thompson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Jessica Martinez',
      email: 'jessica.martinez@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Charles Robinson',
      email: 'charles.robinson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Karen Clark',
      email: 'karen.clark@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Thomas Rodriguez',
      email: 'thomas.rodriguez@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Nancy Lewis',
      email: 'nancy.lewis@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Paul Lee',
      email: 'paul.lee@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Betty Walker',
      email: 'betty.walker@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Mark Hall',
      email: 'mark.hall@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Helen Allen',
      email: 'helen.allen@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Donald Young',
      email: 'donald.young@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Sandra King',
      email: 'sandra.king@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'George Wright',
      email: 'george.wright@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Dorothy Scott',
      email: 'dorothy.scott@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Kenneth Green',
      email: 'kenneth.green@example.com',
      password: 'Zaq12wsx',
      role: UserRole.admin,
    },
  ],
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    // Additional 30 products for variety
    {
      name: 'Premium Cotton T-Shirt',
      slug: 'premium-cotton-t-shirt',
      category: "Men's T-Shirts",
      description: 'Ultra-soft 100% organic cotton for everyday comfort',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 29.99,
      brand: 'EcoWear',
      rating: 4.5,
      numReviews: 45,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Athletic Performance Polo',
      slug: 'athletic-performance-polo',
      category: "Men's Sportswear",
      description: 'Moisture-wicking fabric for active lifestyles',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 44.99,
      brand: 'SportMax',
      rating: 4.3,
      numReviews: 28,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Business Casual Oxford',
      slug: 'business-casual-oxford',
      category: "Men's Dress Shirts",
      description: 'Perfect blend of professional and comfortable',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 67.50,
      brand: 'Executive',
      rating: 4.7,
      numReviews: 33,
      stock: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Vintage Denim Jacket',
      slug: 'vintage-denim-jacket',
      category: "Men's Jackets",
      description: 'Classic American style with modern fit',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 89.99,
      brand: 'Heritage',
      rating: 4.8,
      numReviews: 52,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Silk Blend Formal Shirt',
      slug: 'silk-blend-formal-shirt',
      category: "Men's Formal Wear",
      description: 'Luxurious silk-cotton blend for special occasions',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 125.00,
      brand: 'Elegance',
      rating: 4.9,
      numReviews: 15,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Casual Summer Linen Shirt',
      slug: 'casual-summer-linen-shirt',
      category: "Men's Casual Wear",
      description: 'Breathable linen perfect for warm weather',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 54.99,
      brand: 'Coastal',
      rating: 4.4,
      numReviews: 37,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tech Fleece Hoodie',
      slug: 'tech-fleece-hoodie',
      category: "Men's Sweatshirts",
      description: 'Innovative fleece technology for ultimate warmth',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 78.00,
      brand: 'TechWear',
      rating: 4.6,
      numReviews: 61,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Merino Wool Sweater',
      slug: 'merino-wool-sweater',
      category: "Men's Sweaters",
      description: 'Premium merino wool for sophisticated style',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 98.50,
      brand: 'Nordic',
      rating: 4.7,
      numReviews: 22,
      stock: 9,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Canvas Work Shirt',
      slug: 'canvas-work-shirt',
      category: "Men's Workwear",
      description: 'Durable canvas construction for tough jobs',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 42.99,
      brand: 'WorkPro',
      rating: 4.2,
      numReviews: 18,
      stock: 30,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Slim Fit Chinos',
      slug: 'slim-fit-chinos',
      category: "Men's Pants",
      description: 'Modern slim fit with stretch comfort',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 59.99,
      brand: 'ModernFit',
      rating: 4.5,
      numReviews: 40,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Leather Bomber Jacket',
      slug: 'leather-bomber-jacket',
      category: "Men's Jackets",
      description: 'Genuine leather with vintage bomber style',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 299.99,
      brand: 'Aviation',
      rating: 4.9,
      numReviews: 8,
      stock: 3,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Quick Dry Swim Shorts',
      slug: 'quick-dry-swim-shorts',
      category: "Men's Swimwear",
      description: 'Fast-drying fabric with UV protection',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 34.99,
      brand: 'AquaFit',
      rating: 4.3,
      numReviews: 26,
      stock: 35,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Bamboo Fiber Polo',
      slug: 'bamboo-fiber-polo',
      category: "Men's Eco-Friendly",
      description: 'Sustainable bamboo fabric with natural properties',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 48.00,
      brand: 'GreenLife',
      rating: 4.6,
      numReviews: 31,
      stock: 16,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Thermal Henley Shirt',
      slug: 'thermal-henley-shirt',
      category: "Men's Thermals",
      description: 'Waffle-knit thermal for layering',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 32.50,
      brand: 'WarmTech',
      rating: 4.4,
      numReviews: 19,
      stock: 28,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Designer Graphic Tee',
      slug: 'designer-graphic-tee',
      category: "Men's T-Shirts",
      description: 'Limited edition artistic prints',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 39.99,
      brand: 'ArtWear',
      rating: 4.5,
      numReviews: 55,
      stock: 14,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Cargo Utility Pants',
      slug: 'cargo-utility-pants',
      category: "Men's Pants",
      description: 'Multiple pockets with tactical design',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 64.99,
      brand: 'Tactical',
      rating: 4.3,
      numReviews: 24,
      stock: 19,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Cashmere V-Neck',
      slug: 'cashmere-v-neck',
      category: "Men's Luxury",
      description: 'Pure cashmere for ultimate luxury',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 189.00,
      brand: 'Luxe',
      rating: 4.8,
      numReviews: 11,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Rain Resistant Windbreaker',
      slug: 'rain-resistant-windbreaker',
      category: "Men's Outerwear",
      description: 'Lightweight protection from wind and rain',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 56.99,
      brand: 'WeatherGuard',
      rating: 4.4,
      numReviews: 42,
      stock: 24,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Flannel Plaid Shirt',
      slug: 'flannel-plaid-shirt',
      category: "Men's Casual Wear",
      description: 'Soft brushed cotton in classic plaid',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 45.99,
      brand: 'Lumberjack',
      rating: 4.6,
      numReviews: 38,
      stock: 21,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Performance Golf Polo',
      slug: 'performance-golf-polo',
      category: "Men's Golf Wear",
      description: 'UV protection with moisture management',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 72.00,
      brand: 'ProGolf',
      rating: 4.7,
      numReviews: 16,
      stock: 13,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Stretch Denim Jeans',
      slug: 'stretch-denim-jeans',
      category: "Men's Jeans",
      description: 'Comfort stretch denim in classic fit',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 68.50,
      brand: 'DenimCo',
      rating: 4.5,
      numReviews: 67,
      stock: 26,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Quilted Vest',
      slug: 'quilted-vest',
      category: "Men's Vests",
      description: 'Lightweight quilted design for layering',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 88.00,
      brand: 'Alpine',
      rating: 4.4,
      numReviews: 20,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Moisture Control Undershirt',
      slug: 'moisture-control-undershirt',
      category: "Men's Underwear",
      description: 'Advanced fabric technology for all-day freshness',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 24.99,
      brand: 'FreshTech',
      rating: 4.3,
      numReviews: 49,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Reversible Belt',
      slug: 'reversible-belt',
      category: "Men's Accessories",
      description: 'Two looks in one with reversible design',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 42.00,
      brand: 'Essentials',
      rating: 4.2,
      numReviews: 23,
      stock: 32,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Compression Athletic Shorts',
      slug: 'compression-athletic-shorts',
      category: "Men's Sportswear",
      description: 'Muscle support for intense workouts',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 36.99,
      brand: 'PowerFit',
      rating: 4.5,
      numReviews: 34,
      stock: 27,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tweed Blazer',
      slug: 'tweed-blazer',
      category: "Men's Blazers",
      description: 'Classic British style in premium tweed',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 225.00,
      brand: 'Heritage',
      rating: 4.8,
      numReviews: 9,
      stock: 4,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Base Layer Thermal Set',
      slug: 'base-layer-thermal-set',
      category: "Men's Thermals",
      description: 'Complete thermal underwear set for cold weather',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 58.99,
      brand: 'Arctic',
      rating: 4.6,
      numReviews: 27,
      stock: 17,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Suede Desert Boots',
      slug: 'suede-desert-boots',
      category: "Men's Footwear",
      description: 'Classic desert boots in premium suede',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 135.00,
      brand: 'Walkman',
      rating: 4.7,
      numReviews: 41,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Packable Down Jacket',
      slug: 'packable-down-jacket',
      category: "Men's Outerwear",
      description: 'Ultra-light down that packs into its own pocket',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 149.99,
      brand: 'Expedition',
      rating: 4.8,
      numReviews: 36,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Organic Cotton Socks Set',
      slug: 'organic-cotton-socks-set',
      category: "Men's Accessories",
      description: 'Pack of 6 comfortable organic cotton socks',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 28.99,
      brand: 'ComfortPlus',
      rating: 4.4,
      numReviews: 58,
      stock: 45,
      isFeatured: false,
      banner: null,
    },
  ],
  orders: [
    // Order 1 - Delivered
    {
      userEmail: 'user@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Jane Doe',
        street: 'ul. Marszałkowska 10',
        city: 'Warszawa',
        zipCode: '00-626',
        country: 'Polska',
        phone: '48123456789',
        state: 'Mazowieckie',
      },
      items: [
        { slug: 'polo-sporting-stretch-shirt', qty: 2 },
        { slug: 'brooks-brothers-long-sleeved-shirt', qty: 1 },
      ],
      status: 'delivered',
      isPaid: true,
      isDelivered: true,
      paidAt: new Date('2025-08-10'),
      deliveredAt: new Date('2025-08-15'),
      createdAt: new Date('2025-08-08'),
    },
    // Order 2 - Pending
    {
      userEmail: 'robert.johnson@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Robert Johnson',
        street: 'ul. Krakowskie Przedmieście 42',
        city: 'Kraków',
        zipCode: '30-071',
        country: 'Polska',
        phone: '48987654321',
        state: 'Małopolskie',
      },
      items: [
        { slug: 'tommy-hilfiger-classic-fit-dress-shirt', qty: 1 },
      ],
      status: 'pending',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-15'),
    },
    // Order 3 - Processing
    {
      userEmail: 'maria.garcia@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Maria Garcia',
        street: 'ul. Piotrkowska 100',
        city: 'Łódź',
        zipCode: '90-004',
        country: 'Polska',
        phone: '48555123456',
        state: 'Łódzkie',
      },
      items: [
        { slug: 'calvin-klein-slim-fit-stretch-shirt', qty: 3 },
        { slug: 'polo-classic-pink-hoodie', qty: 1 },
      ],
      status: 'processing',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-14'),
      createdAt: new Date('2025-09-14'),
    },
    // Order 4 - Shipped
    {
      userEmail: 'david.smith@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'David Smith',
        street: 'ul. Długa 23',
        city: 'Gdańsk',
        zipCode: '80-831',
        country: 'Polska',
        phone: '48666777888',
        state: 'Pomorskie',
      },
      items: [
        { slug: 'nike-crew-neck-sweatshirt', qty: 2 },
      ],
      status: 'shipped',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-12'),
      createdAt: new Date('2025-09-11'),
    },
    // Order 5 - Cancelled
    {
      userEmail: 'sarah.williams@example.com',
      paymentMethod: 'Cash on Delivery',
      shippingAddress: {
        fullName: 'Sarah Williams',
        street: 'ul. Rynek 1',
        city: 'Wrocław',
        zipCode: '50-996',
        country: 'Polska',
        phone: '48777888999',
        state: 'Dolnośląskie',
      },
      items: [
        { slug: 'adidas-performance-hooded-sweatshirt', qty: 1 },
        { slug: 'thermal-base-layer', qty: 2 },
      ],
      status: 'cancelled',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-10'),
    },
    // Order 6 - Delivered
    {
      userEmail: 'michael.brown@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Michael Brown',
        street: 'ul. Świętojańska 15',
        city: 'Poznań',
        zipCode: '61-113',
        country: 'Polska',
        phone: '48500600700',
        state: 'Wielkopolskie',
      },
      items: [
        { slug: 'polo-ralph-lauren-oxford-shirt', qty: 2 },
        { slug: 'reversible-belt', qty: 1 },
      ],
      status: 'delivered',
      isPaid: true,
      isDelivered: true,
      paidAt: new Date('2025-09-01'),
      deliveredAt: new Date('2025-09-05'),
      createdAt: new Date('2025-09-01'),
    },
    // Order 7 - Processing
    {
      userEmail: 'jennifer.davis@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Jennifer Davis',
        street: 'ul. Zamkowa 8',
        city: 'Lublin',
        zipCode: '20-109',
        country: 'Polska',
        phone: '48111222333',
        state: 'Lubelskie',
      },
      items: [
        { slug: 'the-north-face-alpenglow', qty: 1 },
      ],
      status: 'processing',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-15'),
      createdAt: new Date('2025-09-15'),
    },
    // Order 8 - Pending
    {
      userEmail: 'william.miller@example.com',
      paymentMethod: 'Cash on Delivery',
      shippingAddress: {
        fullName: 'William Miller',
        street: 'ul. Główna 45',
        city: 'Katowice',
        zipCode: '40-001',
        country: 'Polska',
        phone: '48222333444',
        state: 'Śląskie',
      },
      items: [
        { slug: 'fleece-pullover', qty: 2 },
        { slug: 'organic-cotton-socks-set', qty: 1 },
      ],
      status: 'pending',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-16'),
    },
    // Order 9 - Shipped
    {
      userEmail: 'elizabeth.wilson@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Elizabeth Wilson',
        street: 'ul. Mickiewicza 20',
        city: 'Białystok',
        zipCode: '15-232',
        country: 'Polska',
        phone: '48333444555',
        state: 'Podlaskie',
      },
      items: [
        { slug: 'under-armour-insulated-jacket', qty: 1 },
        { slug: 'compression-athletic-shorts', qty: 2 },
      ],
      status: 'shipped',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-13'),
      createdAt: new Date('2025-09-13'),
    },
    // Order 10 - Delivered
    {
      userEmail: 'james.moore@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'James Moore',
        street: 'ul. Portowa 7',
        city: 'Szczecin',
        zipCode: '70-001',
        country: 'Polska',
        phone: '48444555666',
        state: 'Zachodniopomorskie',
      },
      items: [
        { slug: 'woolrich-puffer-coat', qty: 1 },
      ],
      status: 'delivered',
      isPaid: true,
      isDelivered: true,
      paidAt: new Date('2025-08-20'),
      deliveredAt: new Date('2025-08-25'),
      createdAt: new Date('2025-08-20'),
    },
    // Order 11 - Processing
    {
      userEmail: 'patricia.taylor@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Patricia Taylor',
        street: 'ul. Kościuszki 30',
        city: 'Rzeszów',
        zipCode: '35-030',
        country: 'Polska',
        phone: '48555666777',
        state: 'Podkarpackie',
      },
      items: [
        { slug: 'packable-down-jacket', qty: 1 },
        { slug: 'moisture-control-undershirt', qty: 3 },
      ],
      status: 'processing',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-14'),
      createdAt: new Date('2025-09-14'),
    },
    // Order 12 - Cancelled
    {
      userEmail: 'christopher.anderson@example.com',
      paymentMethod: 'Cash on Delivery',
      shippingAddress: {
        fullName: 'Christopher Anderson',
        street: 'ul. Warszawska 55',
        city: 'Kielce',
        zipCode: '25-312',
        country: 'Polska',
        phone: '48666777888',
        state: 'Świętokrzyskie',
      },
      items: [
        { slug: 'champion-zip-up-hoodie', qty: 1 },
      ],
      status: 'cancelled',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-09'),
    },
    // Order 13 - Delivered
    {
      userEmail: 'linda.thomas@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Linda Thomas',
        street: 'ul. Morska 12',
        city: 'Gdynia',
        zipCode: '81-001',
        country: 'Polska',
        phone: '48777888999',
        state: 'Pomorskie',
      },
      items: [
        { slug: 'outdoor-waterproof-jacket', qty: 1 },
        { slug: 'quilted-vest', qty: 1 },
      ],
      status: 'delivered',
      isPaid: true,
      isDelivered: true,
      paidAt: new Date('2025-09-05'),
      deliveredAt: new Date('2025-09-10'),
      createdAt: new Date('2025-09-05'),
    },
    // Order 14 - Pending
    {
      userEmail: 'matthew.jackson@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Matthew Jackson',
        street: 'ul. Słoneczna 18',
        city: 'Olsztyn',
        zipCode: '10-001',
        country: 'Polska',
        phone: '48888999000',
        state: 'Warmińsko-Mazurskie',
      },
      items: [
        { slug: 'polo-sporting-stretch-shirt', qty: 1 },
        { slug: 'calvin-klein-slim-fit-stretch-shirt', qty: 1 },
      ],
      status: 'pending',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-16'),
    },
    // Order 15 - Shipped
    {
      userEmail: 'barbara.white@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Barbara White',
        street: 'ul. Piłsudskiego 22',
        city: 'Opole',
        zipCode: '45-001',
        country: 'Polska',
        phone: '48999000111',
        state: 'Opolskie',
      },
      items: [
        { slug: 'brooks-brothers-long-sleeved-shirt', qty: 2 },
      ],
      status: 'shipped',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-12'),
      createdAt: new Date('2025-09-12'),
    },
    // Order 16 - Processing
    {
      userEmail: 'daniel.harris@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Daniel Harris',
        street: 'ul. Nadwiślańska 4',
        city: 'Toruń',
        zipCode: '87-100',
        country: 'Polska',
        phone: '48100200300',
        state: 'Kujawsko-Pomorskie',
      },
      items: [
        { slug: 'tommy-hilfiger-classic-fit-dress-shirt', qty: 1 },
        { slug: 'reversible-belt', qty: 1 },
      ],
      status: 'processing',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-15'),
      createdAt: new Date('2025-09-15'),
    },
    // Order 17 - Delivered
    {
      userEmail: 'susan.martin@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Susan Martin',
        street: 'ul. Kręta 33',
        city: 'Bydgoszcz',
        zipCode: '85-001',
        country: 'Polska',
        phone: '48200300400',
        state: 'Kujawsko-Pomorskie',
      },
      items: [
        { slug: 'nike-crew-neck-sweatshirt', qty: 1 },
        { slug: 'thermal-base-layer', qty: 2 },
      ],
      status: 'delivered',
      isPaid: true,
      isDelivered: true,
      paidAt: new Date('2025-08-25'),
      deliveredAt: new Date('2025-08-30'),
      createdAt: new Date('2025-08-25'),
    },
    // Order 18 - Cancelled
    {
      userEmail: 'joseph.thompson@example.com',
      paymentMethod: 'Cash on Delivery',
      shippingAddress: {
        fullName: 'Joseph Thompson',
        street: 'ul. Zielona 27',
        city: 'Gorzów Wielkopolski',
        zipCode: '66-400',
        country: 'Polska',
        phone: '48300400500',
        state: 'Lubuskie',
      },
      items: [
        { slug: 'adidas-performance-hooded-sweatshirt', qty: 2 },
      ],
      status: 'cancelled',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-08'),
    },
    // Order 19 - Shipped
    {
      userEmail: 'nancy.martinez@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Nancy Martinez',
        street: 'ul. Szeroka 9',
        city: 'Zielona Góra',
        zipCode: '65-001',
        country: 'Polska',
        phone: '48400500600',
        state: 'Lubuskie',
      },
      items: [
        { slug: 'the-north-face-alpenglow', qty: 1 },
        { slug: 'fleece-pullover', qty: 1 },
      ],
      status: 'shipped',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-11'),
      createdAt: new Date('2025-09-11'),
    },
    // Order 20 - Processing
    {
      userEmail: 'charles.robinson@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Charles Robinson',
        street: 'ul. Kwiatowa 14',
        city: 'Częstochowa',
        zipCode: '42-200',
        country: 'Polska',
        phone: '48500600700',
        state: 'Śląskie',
      },
      items: [
        { slug: 'under-armour-insulated-jacket', qty: 1 },
      ],
      status: 'processing',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-14'),
      createdAt: new Date('2025-09-14'),
    },
    // Order 21 - Delivered
    {
      userEmail: 'admin@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'John Admin',
        street: 'ul. Administracyjna 1',
        city: 'Warszawa',
        zipCode: '00-001',
        country: 'Polska',
        phone: '48600700800',
        state: 'Mazowieckie',
      },
      items: [
        { slug: 'woolrich-puffer-coat', qty: 1 },
        { slug: 'packable-down-jacket', qty: 1 },
      ],
      status: 'delivered',
      isPaid: true,
      isDelivered: true,
      paidAt: new Date('2025-09-02'),
      deliveredAt: new Date('2025-09-07'),
      createdAt: new Date('2025-09-02'),
    },
    // Order 22 - Pending
    {
      userEmail: 'karen.clark@example.com',
      paymentMethod: 'Cash on Delivery',
      shippingAddress: {
        fullName: 'Karen Clark',
        street: 'ul. Parkowa 21',
        city: 'Radom',
        zipCode: '26-600',
        country: 'Polska',
        phone: '48700800900',
        state: 'Mazowieckie',
      },
      items: [
        { slug: 'champion-zip-up-hoodie', qty: 1 },
        { slug: 'organic-cotton-socks-set', qty: 2 },
      ],
      status: 'pending',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-15'),
    },
    // Order 23 - Shipped
    {
      userEmail: 'thomas.rodriguez@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Thomas Rodriguez',
        street: 'ul. Łąkowa 16',
        city: 'Elbląg',
        zipCode: '82-300',
        country: 'Polska',
        phone: '48800900100',
        state: 'Warmińsko-Mazurskie',
      },
      items: [
        { slug: 'outdoor-waterproof-jacket', qty: 1 },
      ],
      status: 'shipped',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-13'),
      createdAt: new Date('2025-09-13'),
    },
    // Order 24 - Processing
    {
      userEmail: 'donna.lewis@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Donna Lewis',
        street: 'ul. Rzeczna 5',
        city: 'Słupsk',
        zipCode: '76-200',
        country: 'Polska',
        phone: '48900100200',
        state: 'Pomorskie',
      },
      items: [
        { slug: 'polo-ralph-lauren-oxford-shirt', qty: 1 },
        { slug: 'moisture-control-undershirt', qty: 2 },
      ],
      status: 'processing',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-15'),
      createdAt: new Date('2025-09-15'),
    },
    // Order 25 - Delivered
    {
      userEmail: 'paul.walker@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Paul Walker',
        street: 'ul. Górna 38',
        city: 'Tarnów',
        zipCode: '33-100',
        country: 'Polska',
        phone: '48101202303',
        state: 'Małopolskie',
      },
      items: [
        { slug: 'quilted-vest', qty: 1 },
        { slug: 'compression-athletic-shorts', qty: 1 },
      ],
      status: 'delivered',
      isPaid: true,
      isDelivered: true,
      paidAt: new Date('2025-08-15'),
      deliveredAt: new Date('2025-08-20'),
      createdAt: new Date('2025-08-15'),
    },
    // Order 26 - Cancelled
    {
      userEmail: 'betty.hall@example.com',
      paymentMethod: 'Cash on Delivery',
      shippingAddress: {
        fullName: 'Betty Hall',
        street: 'ul. Ogrodowa 29',
        city: 'Legnica',
        zipCode: '59-220',
        country: 'Polska',
        phone: '48202303404',
        state: 'Dolnośląskie',
      },
      items: [
        { slug: 'polo-classic-pink-hoodie', qty: 2 },
      ],
      status: 'cancelled',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-07'),
    },
    // Order 27 - Processing
    {
      userEmail: 'user@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Jane User',
        street: 'ul. Testowa 99',
        city: 'Warszawa',
        zipCode: '00-999',
        country: 'Polska',
        phone: '48303404505',
        state: 'Mazowieckie',
      },
      items: [
        { slug: 'brooks-brothers-long-sleeved-shirt', qty: 1 },
        { slug: 'tommy-hilfiger-classic-fit-dress-shirt', qty: 1 },
        { slug: 'calvin-klein-slim-fit-stretch-shirt', qty: 2 },
      ],
      status: 'processing',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-16'),
      createdAt: new Date('2025-09-16'),
    },
    // Order 28 - Shipped
    {
      userEmail: 'kenneth.green@example.com',
      paymentMethod: 'PayPal',
      shippingAddress: {
        fullName: 'Kenneth Green',
        street: 'ul. Boczna 41',
        city: 'Jelenia Góra',
        zipCode: '58-500',
        country: 'Polska',
        phone: '48404505606',
        state: 'Dolnośląskie',
      },
      items: [
        { slug: 'nike-crew-neck-sweatshirt', qty: 1 },
      ],
      status: 'shipped',
      isPaid: true,
      isDelivered: false,
      paidAt: new Date('2025-09-12'),
      createdAt: new Date('2025-09-12'),
    },
    // Order 29 - Pending
    {
      userEmail: 'robert.johnson@example.com',
      paymentMethod: 'Cash on Delivery',
      shippingAddress: {
        fullName: 'Robert Johnson Jr.',
        street: 'ul. Nowa 52',
        city: 'Płock',
        zipCode: '09-400',
        country: 'Polska',
        phone: '48505606707',
        state: 'Mazowieckie',
      },
      items: [
        { slug: 'adidas-performance-hooded-sweatshirt', qty: 1 },
        { slug: 'the-north-face-alpenglow', qty: 1 },
      ],
      status: 'pending',
      isPaid: false,
      isDelivered: false,
      createdAt: new Date('2025-09-16'),
    },
    // Order 30 - Delivered
    {
      userEmail: 'maria.garcia@example.com',
      paymentMethod: 'Stripe',
      shippingAddress: {
        fullName: 'Maria Garcia Lopez',
        street: 'ul. Stara 63',
        city: 'Kalisz',
        zipCode: '62-800',
        country: 'Polska',
        phone: '48606707808',
        state: 'Wielkopolskie',
      },
      items: [
        { slug: 'fleece-pullover', qty: 1 },
        { slug: 'under-armour-insulated-jacket', qty: 1 },
        { slug: 'reversible-belt', qty: 2 },
      ],
      status: 'delivered',
      isPaid: true,
      isDelivered: true,
      paidAt: new Date('2025-08-28'),
      deliveredAt: new Date('2025-09-02'),
      createdAt: new Date('2025-08-28'),
    },
  ],
}

export default sampleData
