import { UserRole } from '@prisma/client'

const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: 'Zaq12wsx',
      role: UserRole.admin,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    // Additional 31 users (3 admins + 28 regular users) for testing
    {
      name: 'Robert Johnson',
      email: 'robert.johnson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Maria Garcia',
      email: 'maria.garcia@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'David Smith',
      email: 'david.smith@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Sarah Williams',
      email: 'sarah.williams@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Michael Brown',
      email: 'michael.brown@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Jennifer Davis',
      email: 'jennifer.davis@example.com',
      password: 'Zaq12wsx',
      role: UserRole.admin,
    },
    {
      name: 'William Miller',
      email: 'william.miller@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Elizabeth Wilson',
      email: 'elizabeth.wilson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'James Moore',
      email: 'james.moore@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Patricia Taylor',
      email: 'patricia.taylor@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Christopher Anderson',
      email: 'christopher.anderson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Linda Thomas',
      email: 'linda.thomas@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Matthew Jackson',
      email: 'matthew.jackson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Barbara White',
      email: 'barbara.white@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Daniel Harris',
      email: 'daniel.harris@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Susan Martin',
      email: 'susan.martin@example.com',
      password: 'Zaq12wsx',
      role: UserRole.admin,
    },
    {
      name: 'Joseph Thompson',
      email: 'joseph.thompson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Jessica Martinez',
      email: 'jessica.martinez@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Charles Robinson',
      email: 'charles.robinson@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Karen Clark',
      email: 'karen.clark@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Thomas Rodriguez',
      email: 'thomas.rodriguez@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Nancy Lewis',
      email: 'nancy.lewis@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Paul Lee',
      email: 'paul.lee@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Betty Walker',
      email: 'betty.walker@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Mark Hall',
      email: 'mark.hall@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Helen Allen',
      email: 'helen.allen@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Donald Young',
      email: 'donald.young@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Sandra King',
      email: 'sandra.king@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'George Wright',
      email: 'george.wright@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Dorothy Scott',
      email: 'dorothy.scott@example.com',
      password: 'Zaq12wsx',
      role: UserRole.user,
    },
    {
      name: 'Kenneth Green',
      email: 'kenneth.green@example.com',
      password: 'Zaq12wsx',
      role: UserRole.admin,
    },
  ],
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    // Additional 30 products for variety
    {
      name: 'Premium Cotton T-Shirt',
      slug: 'premium-cotton-t-shirt',
      category: "Men's T-Shirts",
      description: 'Ultra-soft 100% organic cotton for everyday comfort',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 29.99,
      brand: 'EcoWear',
      rating: 4.5,
      numReviews: 45,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Athletic Performance Polo',
      slug: 'athletic-performance-polo',
      category: "Men's Sportswear",
      description: 'Moisture-wicking fabric for active lifestyles',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 44.99,
      brand: 'SportMax',
      rating: 4.3,
      numReviews: 28,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Business Casual Oxford',
      slug: 'business-casual-oxford',
      category: "Men's Dress Shirts",
      description: 'Perfect blend of professional and comfortable',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 67.50,
      brand: 'Executive',
      rating: 4.7,
      numReviews: 33,
      stock: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Vintage Denim Jacket',
      slug: 'vintage-denim-jacket',
      category: "Men's Jackets",
      description: 'Classic American style with modern fit',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 89.99,
      brand: 'Heritage',
      rating: 4.8,
      numReviews: 52,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Silk Blend Formal Shirt',
      slug: 'silk-blend-formal-shirt',
      category: "Men's Formal Wear",
      description: 'Luxurious silk-cotton blend for special occasions',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 125.00,
      brand: 'Elegance',
      rating: 4.9,
      numReviews: 15,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Casual Summer Linen Shirt',
      slug: 'casual-summer-linen-shirt',
      category: "Men's Casual Wear",
      description: 'Breathable linen perfect for warm weather',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 54.99,
      brand: 'Coastal',
      rating: 4.4,
      numReviews: 37,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tech Fleece Hoodie',
      slug: 'tech-fleece-hoodie',
      category: "Men's Sweatshirts",
      description: 'Innovative fleece technology for ultimate warmth',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 78.00,
      brand: 'TechWear',
      rating: 4.6,
      numReviews: 61,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Merino Wool Sweater',
      slug: 'merino-wool-sweater',
      category: "Men's Sweaters",
      description: 'Premium merino wool for sophisticated style',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 98.50,
      brand: 'Nordic',
      rating: 4.7,
      numReviews: 22,
      stock: 9,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Canvas Work Shirt',
      slug: 'canvas-work-shirt',
      category: "Men's Workwear",
      description: 'Durable canvas construction for tough jobs',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 42.99,
      brand: 'WorkPro',
      rating: 4.2,
      numReviews: 18,
      stock: 30,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Slim Fit Chinos',
      slug: 'slim-fit-chinos',
      category: "Men's Pants",
      description: 'Modern slim fit with stretch comfort',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 59.99,
      brand: 'ModernFit',
      rating: 4.5,
      numReviews: 40,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Leather Bomber Jacket',
      slug: 'leather-bomber-jacket',
      category: "Men's Jackets",
      description: 'Genuine leather with vintage bomber style',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 299.99,
      brand: 'Aviation',
      rating: 4.9,
      numReviews: 8,
      stock: 3,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Quick Dry Swim Shorts',
      slug: 'quick-dry-swim-shorts',
      category: "Men's Swimwear",
      description: 'Fast-drying fabric with UV protection',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 34.99,
      brand: 'AquaFit',
      rating: 4.3,
      numReviews: 26,
      stock: 35,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Bamboo Fiber Polo',
      slug: 'bamboo-fiber-polo',
      category: "Men's Eco-Friendly",
      description: 'Sustainable bamboo fabric with natural properties',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 48.00,
      brand: 'GreenLife',
      rating: 4.6,
      numReviews: 31,
      stock: 16,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Thermal Henley Shirt',
      slug: 'thermal-henley-shirt',
      category: "Men's Thermals",
      description: 'Waffle-knit thermal for layering',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 32.50,
      brand: 'WarmTech',
      rating: 4.4,
      numReviews: 19,
      stock: 28,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Designer Graphic Tee',
      slug: 'designer-graphic-tee',
      category: "Men's T-Shirts",
      description: 'Limited edition artistic prints',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 39.99,
      brand: 'ArtWear',
      rating: 4.5,
      numReviews: 55,
      stock: 14,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Cargo Utility Pants',
      slug: 'cargo-utility-pants',
      category: "Men's Pants",
      description: 'Multiple pockets with tactical design',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 64.99,
      brand: 'Tactical',
      rating: 4.3,
      numReviews: 24,
      stock: 19,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Cashmere V-Neck',
      slug: 'cashmere-v-neck',
      category: "Men's Luxury",
      description: 'Pure cashmere for ultimate luxury',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 189.00,
      brand: 'Luxe',
      rating: 4.8,
      numReviews: 11,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Rain Resistant Windbreaker',
      slug: 'rain-resistant-windbreaker',
      category: "Men's Outerwear",
      description: 'Lightweight protection from wind and rain',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 56.99,
      brand: 'WeatherGuard',
      rating: 4.4,
      numReviews: 42,
      stock: 24,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Flannel Plaid Shirt',
      slug: 'flannel-plaid-shirt',
      category: "Men's Casual Wear",
      description: 'Soft brushed cotton in classic plaid',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 45.99,
      brand: 'Lumberjack',
      rating: 4.6,
      numReviews: 38,
      stock: 21,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Performance Golf Polo',
      slug: 'performance-golf-polo',
      category: "Men's Golf Wear",
      description: 'UV protection with moisture management',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 72.00,
      brand: 'ProGolf',
      rating: 4.7,
      numReviews: 16,
      stock: 13,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Stretch Denim Jeans',
      slug: 'stretch-denim-jeans',
      category: "Men's Jeans",
      description: 'Comfort stretch denim in classic fit',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 68.50,
      brand: 'DenimCo',
      rating: 4.5,
      numReviews: 67,
      stock: 26,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Quilted Vest',
      slug: 'quilted-vest',
      category: "Men's Vests",
      description: 'Lightweight quilted design for layering',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 88.00,
      brand: 'Alpine',
      rating: 4.4,
      numReviews: 20,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Moisture Control Undershirt',
      slug: 'moisture-control-undershirt',
      category: "Men's Underwear",
      description: 'Advanced fabric technology for all-day freshness',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 24.99,
      brand: 'FreshTech',
      rating: 4.3,
      numReviews: 49,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Reversible Belt',
      slug: 'reversible-belt',
      category: "Men's Accessories",
      description: 'Two looks in one with reversible design',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 42.00,
      brand: 'Essentials',
      rating: 4.2,
      numReviews: 23,
      stock: 32,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Compression Athletic Shorts',
      slug: 'compression-athletic-shorts',
      category: "Men's Sportswear",
      description: 'Muscle support for intense workouts',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 36.99,
      brand: 'PowerFit',
      rating: 4.5,
      numReviews: 34,
      stock: 27,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tweed Blazer',
      slug: 'tweed-blazer',
      category: "Men's Blazers",
      description: 'Classic British style in premium tweed',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 225.00,
      brand: 'Heritage',
      rating: 4.8,
      numReviews: 9,
      stock: 4,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Base Layer Thermal Set',
      slug: 'base-layer-thermal-set',
      category: "Men's Thermals",
      description: 'Complete thermal underwear set for cold weather',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 58.99,
      brand: 'Arctic',
      rating: 4.6,
      numReviews: 27,
      stock: 17,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Suede Desert Boots',
      slug: 'suede-desert-boots',
      category: "Men's Footwear",
      description: 'Classic desert boots in premium suede',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 135.00,
      brand: 'Walkman',
      rating: 4.7,
      numReviews: 41,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Packable Down Jacket',
      slug: 'packable-down-jacket',
      category: "Men's Outerwear",
      description: 'Ultra-light down that packs into its own pocket',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 149.99,
      brand: 'Expedition',
      rating: 4.8,
      numReviews: 36,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Organic Cotton Socks Set',
      slug: 'organic-cotton-socks-set',
      category: "Men's Accessories",
      description: 'Pack of 6 comfortable organic cotton socks',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 28.99,
      brand: 'ComfortPlus',
      rating: 4.4,
      numReviews: 58,
      stock: 45,
      isFeatured: false,
      banner: null,
    },
  ],
}

export default sampleData
